#ifndef _TASK_CONF_H_
#define _TASK_CONF_H_

#ifndef TASK_PREEMPTION_TIMESLICE_US
#define TASK_PREEMPTION_TIMESLICE_US	(10 * 1000) /* 10 ms */
#endif

#ifndef TASK_MAX_TASKS
#define TASK_MAX_TASKS			16U
#endif

#ifndef TASK_DEFAULT_PRIORITY
#define TASK_DEFAULT_PRIORITY		0U
#endif

#ifndef TASK_DEFAULT_STACK_SIZE
#define TASK_DEFAULT_STACK_SIZE		512U
#endif

#endif /* _TASK_CONF_H_ */
